# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ToDoList' do
pod 'PubNub', "~> 4.1"


end

